# Generated by Django 4.2.27 on 2026-01-20 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_flag', models.CharField(blank=True, db_index=True, help_text='用户唯一标识符，用于区分不同使用者（一个用户可以有多个 Stake 账号）', max_length=100, null=True, verbose_name='用户标识')),
                ('stake_account_id', models.CharField(blank=True, help_text='当前用户下的 Stake 账号（对应 StakeAccount.stake_account_id）', max_length=100, null=True, verbose_name='Stake账号ID')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='红包代码')),
                ('status', models.CharField(choices=[('claim_success', '✅ 领取成功'), ('claim_failure', '❌ 领取失败'), ('inactive', '⌛ 次数领取完'), ('not_found', '❌ 找不到'), ('session_expired', '⚠️ 会话已过期'), ('already_claimed', '🔁 已领过'), ('weekly_wager_requirement', '📋 流水不够'), ('drop_unavailable', '⏰ 7天内不能领代码'), ('error_403', '⚠️ 403错误'), ('error', '❓ 其他错误')], max_length=30, verbose_name='状态')),
                ('bonus_value', models.CharField(blank=True, help_text="格式：金额 货币，如 '1.5 USDT'", max_length=50, null=True, verbose_name='奖金金额（显示用）')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=8, help_text='纯数字，便于计算', max_digits=20, null=True, verbose_name='奖金数值')),
                ('bonus_currency', models.CharField(blank=True, help_text='如：USDT, BTC, ETH', max_length=10, null=True, verbose_name='货币类型')),
                ('response_time_ms', models.IntegerField(null=True, verbose_name='响应时间(ms)')),
                ('is_retry', models.BooleanField(default=False, verbose_name='是否重试')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('query_response_body', models.TextField(blank=True, help_text='记录查询代码是否可用的API响应内容（第一步接口）', null=True, verbose_name='查询接口响应体')),
                ('claim_response_body', models.TextField(blank=True, help_text='记录领取代码的API响应内容（第二步接口，仅当代码可用时才有）', null=True, verbose_name='领取接口响应体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, help_text='关联的前端用户（新数据直接关联，老数据通过 user_flag 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '领取明细',
                'verbose_name_plural': '领取明细',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'status'], name='serverbot_c_code_e0f5e2_idx'), models.Index(fields=['created_at'], name='serverbot_c_created_6a2f56_idx'), models.Index(fields=['user_flag', 'created_at'], name='serverbot_c_user_fl_39b341_idx'), models.Index(fields=['user', 'created_at'], name='serverbot_c_user_id_e6d3f3_idx')],
            },
        ),
    ]
