# Generated by Django 6.0 on 2025-12-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0005_stakeaccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='红包代码')),
                ('actual_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='实际价值')),
                ('is_timeout_trigger', models.BooleanField(default=False, verbose_name='是否超时盲冲')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '推送记录',
            },
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('bonus_value', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('is_retry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverbot.stakeaccount')),
                ('code_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serverbot.coderecord')),
            ],
            options={
                'verbose_name': '领取明细',
            },
        ),
    ]
