# Generated by Django 6.0 on 2025-12-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakeAccount',
            fields=[
                ('account_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='账号ID')),
                ('token', models.TextField(verbose_name='Access Token')),
                ('proxy', models.TextField(verbose_name='代理地址')),
                ('cookies_json', models.TextField(blank=True, null=True, verbose_name='Cookies 数据')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
        ),
    ]
