# Generated by Django 6.0 on 2025-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0003_proxypool_remove_stakeaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeaccount',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='只有脚本运行成功后才会更新此时间', null=True, verbose_name='最后过盾时间'),
        ),
    ]
