# Generated by Django 6.0 on 2025-12-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0004_alter_stakeaccount_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
