# Generated by Django 6.0 on 2025-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0006_coderecord_claimrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeaccount',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='stakeaccount',
            name='bypass_success_time',
            field=models.DateTimeField(blank=True, help_text='过盾成功且数据写入数据库的时间点', null=True, verbose_name='写入过盾时间'),
        ),
        migrations.AddField(
            model_name='stakeaccount',
            name='bypass_trigger_time',
            field=models.DateTimeField(blank=True, help_text='脚本开始尝试过盾的时间点', null=True, verbose_name='触发过盾时间'),
        ),
    ]
