"""
Django settings for manager project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR 是 core/manager/ 目录，需要向上两级到项目根目录
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # 项目根目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=!mnjnimgbng&fv(nvyw9=3bxrp)ew*8&(71qj4__7a@6*ew63'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 允许所有主机访问（生产环境建议指定具体IP或域名）
# 或者指定具体IP：
# ALLOWED_HOSTS = ['146.103.42.142', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # 必须在 admin 之前（如果已安装 django-jazzmin）
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'serverbot.apps.ServerbotConfig',  # Stake 业务
    'otherbot.apps.OtherbotConfig',    # 其他网站业务（完全隔离）
]

# 默认主键字段类型（Django 3.2+ 要求）
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 确保数据库目录存在
db_dir = BASE_DIR / 'db'
os.makedirs(db_dir, exist_ok=True)

# 数据库路径（转换为字符串）
db_path = str(BASE_DIR / 'db' / 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_path,  # 指向项目根目录/db/db.sqlite3
        'OPTIONS': {
            'timeout': 20,  # 允许线程排队等待 20 秒，直到锁释放
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 语言设置为中文
LANGUAGE_CODE = 'zh-hans'

# 时区设置为中国标准时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 必须设置为 False，否则数据库存的时间可能和北京时间差 8 小时
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
