# Generated by Django 6.0 on 2025-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeaccount',
            name='username',
            field=models.CharField(default='', help_text='请输入Stake用户名', max_length=100, verbose_name='Stake用户名'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='account_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='系统内部ID'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后过盾时间'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='proxy',
            field=models.TextField(default='', help_text='格式: http://user:pass@host:port', verbose_name='代理地址'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='token',
            field=models.TextField(default='', help_text='请输入令牌', verbose_name='Stake令牌'),
        ),
    ]
