# Generated by Django 6.0 on 2025-12-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverbot', '0002_stakeaccount_username_alter_stakeaccount_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='代理地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
        ),
        migrations.RemoveField(
            model_name='stakeaccount',
            name='account_id',
        ),
        migrations.AddField(
            model_name='stakeaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='token',
            field=models.TextField(default='', verbose_name='Stake令牌'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Stake用户名'),
        ),
        migrations.AlterField(
            model_name='stakeaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serverbot.proxypool', verbose_name='关联代理'),
        ),
    ]
